# Generated by Django 3.2.6 on 2021-08-19 06:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0003_auto_20210819_0654'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderDetail',
            new_name='Order',
        ),
    ]
