# Generated by Django 3.2.6 on 2021-08-21 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_alter_order_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='accepted',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
